import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import AuthProvider from "./auth/AuthProvider";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="min-h-full flex flex-col">
        <Theme appearance="light" accentColor="purple">
          <QueryClientProvider>
            <AuthProvider>
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </AuthProvider>
          </QueryClientProvider>
        </Theme>
      </body>
    </html>
  );
}
